from __future__ import annotations

from typing import Protocol

from l2_brain.contracts import Command, Effect, Frame, MotorIntent, Observation, TelemetryEvent, TickRecord


class FrameSource(Protocol):
    def initialize(self) -> None: ...

    def reset_episode(self, seed: int | None = None) -> None: ...

    def latest(self) -> Frame: ...

    def close(self) -> None: ...


class TelemetrySource(Protocol):
    def initialize(self) -> None: ...

    def reset_episode(self, seed: int | None = None) -> None: ...

    def poll(self) -> tuple[TelemetryEvent, ...]: ...

    def close(self) -> None: ...


class VisualEncoder(Protocol):
    def initialize(self) -> None: ...

    def reset_episode(self, seed: int | None = None) -> None: ...

    def encode(
        self,
        frame: Frame,
        telemetry: tuple[TelemetryEvent, ...],
        previous: Observation | None,
        now_ns: int,
        stale: bool,
    ) -> Observation: ...

    def close(self) -> None: ...


class CircuitController(Protocol):
    name: str

    def initialize(self) -> None: ...

    def reset_state(self) -> None: ...

    def reset_weights(self) -> None: ...

    def step(self, observation: Observation, now_ns: int, intent_ttl_ns: int) -> MotorIntent: ...

    def close(self) -> None: ...


class ActionDecoder(Protocol):
    def initialize(self) -> None: ...

    def decode(self, intent: MotorIntent, now_ns: int) -> Command: ...

    def close(self) -> None: ...


class InputBackend(Protocol):
    def initialize(self) -> None: ...

    def reset_episode(self, seed: int | None = None) -> None: ...

    def apply(self, command: Command) -> Effect: ...

    def emergency_stop(self) -> None: ...

    def close(self) -> None: ...


class Recorder(Protocol):
    def initialize(self) -> None: ...

    def write(self, record: TickRecord) -> None: ...

    def close(self) -> None: ...


class Evaluator(Protocol):
    def initialize(self) -> None: ...

    def observe(self, record: TickRecord) -> None: ...

    def summary(self) -> dict[str, float | int | str | bool]: ...

    def close(self) -> None: ...
